# dockerproxy docker compose configuration

---
version: '3'
services:
  nginx:
    image: nginx:1.15.10
    container_name: nginx
    depends_on:
      - certbot
    restart: always
    networks:
      - gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - /volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /volumes/nginx/cache/:/etc/nginx/cache/
      - /volumes/nginx/html/:/usr/share/nginx/html/
      - /volumes/acme/:/etc/letsencrypt/
    #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    networks:
      - gateway
    volumes:
      - /volumes/acme/:/etc/letsencrypt/
      - /volumes/acme/:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  gateway: {}
